### PR TITLE
Change link colours

### PR DESCRIPTION
**Pull request by nottrobin**
*Merge #37 first*

As per #35.

QA
--

*Merge #37 first*

`npm i`, `gulp build`, open `demo/index.html`, see that the links are blue and that the nav links are black but blue on hover.

### CODE REVIEW

**Comment by pmahnke** [comment]
@nottrobin there is a conflict with the demo/index.html?  fix and I will appove

**Comment by nottrobin** [comment]
On hold so I can update with what we discussed in https://github.com/ubuntudesign/vanilla-design/issues/1.

**Comment by nottrobin** [comment]
[Changes from design workshop](https://trello.com/c/In0UcniO/2218-changes-from-design-workshop)

**Comment by nottrobin** [comment]
@pmahnke this is ready again, but please merge #37 first.

**Review by pmahnke — APPROVED** [review]
LGTM 👍

**Pull request merged**
